import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <BithumbHeader />
                {children}
            </body>
        </html>
    );
}

function BithumbHeader() {
    // logo, 상단 탭, 검색, 설정
    return (
        <header>
            logo
            <nav>
                <button>거래소</button>
                <button>시장동향</button>
            </nav>
            <button>검색</button>
            <button>설정</button>
        </header>
    );
}
