import type { Metadata, Viewport } from "next";
import localFont from "next/font/local";
import "./globals.css";

const bithumbFont = localFont({
    src: [
        {
            path: "../public/bithumb/fonts/BithumbTradingSans-Regular.woff2",
            weight: "400",
            style: "normal",
        },
        {
            path: "../public/bithumb/fonts/BithumbTradingSans-Medium.woff2",
            weight: "500",
            style: "normal",
        },
        {
            path: "../public/bithumb/fonts/BithumbTradingSans-Semibold.woff2",
            weight: "600",
            style: "normal",
        },
        {
            path: "../public/bithumb/fonts/BithumbTradingSans-Bold.woff2",
            weight: "700",
            style: "normal",
        },
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export const viewport: Viewport = {
    width: "device-width",
    initialScale: 1,
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body
                className={`${bithumbFont.className} antialiased w-full flex justify-center mx-auto max-w-3xl bg-gray-200`}
            >
                {children}
            </body>
        </html>
    );
}
